In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.9 MB 7.1 MB/s eta 0:00:02
   ---------------------- ----------------- 7.3/12.9 MB 20.6 MB/s eta 0:00:01
   ---------------------------------------  12.8/12.9 MB 23.0 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 21.8 MB/s eta 0:00:00


In [1]:
import numpy as np
print(np.__version__)

2.1.0


In [3]:
ar = np.array([1,2,3,4,5])
print(ar)
print(type(ar))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr = np.array((1,2,3,4,5))
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


1-d, 2-d array

In [8]:
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_1d.ndim)
print(arr_2d.ndim)

1
2


higher dimension array

In [9]:
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [14]:
print(arr[0][0][0][0][0])
print(arr[0, 0 , 0, 0, 0])
print(arr[0, 0 , 0, 0, -1])

1
1
5


numpy array slicing

In [18]:
arr = np.array([1,2,3,4,5])
print(arr[1:5])
print(arr[:5])
print(arr[5:])
print(arr[-3:-1])
print(arr[:-3])
print(arr[-3:])
print(arr[1:5:2]) # step

[2 3 4 5]
[1 2 3 4 5]
[]
[3 4]
[1 2]
[3 4 5]
[2 4]


In [20]:
# entire array
print(arr[::2])
print(arr[::3])
print(arr[::1])

[1 3 5]
[1 4]
[1 2 3 4 5]


In [21]:
# type
print(arr.dtype)

int64


In [22]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [24]:
# defined data type
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)
print(type(arr))
# defined data type
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)
print(type(arr))

[b'1' b'2' b'3' b'4']
|S1
<class 'numpy.ndarray'>
[1 2 3 4]
int32
<class 'numpy.ndarray'>


In [25]:
# convert data type on existing arrays
arr = np.array([1.1,2,3.1,4.1,5.1])
newarr = arr.astype('i') # newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3 4 5]
int32


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]
[31  2  3  4  5]
[31  2  3  4  5]


In [40]:
# shape, reshape
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)
newarr = arr.reshape(2,2)

print(newarr)
print(newarr.base) # la 1 view
# unknown dimension
newarr = arr.reshape(2,2,-1)
print(newarr)
# flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[[1 2]
 [3 4]]
[1 2 3 4]
[[[1]
  [2]]

 [[3]
  [4]]]
[1 2 3 4 5 6]


In [41]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [44]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [45]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [46]:
for idx,x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [53]:
# joining
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 1 2 3]


In [50]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [51]:
# stack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [54]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [56]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [6]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,5)
print(newarr)
print(newarr[0], newarr[0][0])

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]
[1 2] 1


In [7]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
print(newarr)
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [13]:
arr = np.array([1,2,3,4,5,4,3,2,1])
x = np.where(arr == 4)
print(x)

(array([3, 5]),)


In [15]:
x= np.where(arr%2  == 0)
print(x)
y= np.where(arr%2 == 1)
print(y)

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6, 8]),)


In [16]:
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7)
print(x)

1


In [19]:
arr = np.array([3,2,0,1])
arr = np.sort(arr)
print(arr)
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
arr = np.array([True, False, True])

print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


In [20]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# filter

In [23]:
import numpy as np
arr = np.array([41,42,43,44])
x= [True, False, True, False]
print(type(x))
print(type(arr))
newarr = arr[x]
print(newarr)
print(type(newarr))

<class 'list'>
<class 'numpy.ndarray'>
[41 43]
<class 'numpy.ndarray'>


In [25]:
arr = np.array([41,42,43,44])
filter_arr = []
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr, newarr)

[False, False, True, True] [43 44]


In [26]:
# directly
filter_arr = arr>42
print(filter_arr)
newarr = arr[filter_arr]
print(newarr)

[False False  True  True]
[43 44]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = (arr % 2 == 0)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
