In [2]:
import numpy as np
x = [1,2,3,4]
y = [4,5,6,7]
z = np.add(x,y)
print(z)

[ 5  7  9 11]


In [7]:
import numpy as np
def myadd(x, y):
    return x+y
myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1,2,3,4], [5,6,7,8]))
print(myadd(1,2))

[6 8 10 12]
3


In [9]:
# add
# subtract
# multiply
# divide
# power
# mod
# divmod
# absolute
x = [1,2,3,4]
y = [4,5,6,7]
z = np.divmod(y,x)
print(z)

(array([4, 2, 2, 1]), array([0, 1, 0, 3]))


In [14]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)
arr = np.fix([-3.1666666, 3.666666667])
print(arr)
arr = np.around(3.1666, 2)

print(arr)
arr = np.floor([-3.1666, 3.6667])

print(arr)
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


In [15]:
arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [16]:
arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [17]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [19]:
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]
